name: Workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Build and run all tests and checks
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.8.15"

      - uses: Gr1N/setup-poetry@v7
        name: Install poetry
        with:
          poetry-version: 1.2.2

      - name: Install python dependencies
        run: make setup

      - name: Check types
        run: make lint

      - name: Check formatting
        run: make format

      - name: Run test
        run: make test

      # Docker stuff
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          push: false
          tags: whylabs/whylogs:py-${{ github.sha }}
          outputs: type=docker,dest=/tmp/whylogs-container.tar
      - name: Upload container artifact
        if: ${{ !github.event.act }}
        uses: actions/upload-artifact@v2
        with:
          name: container
          path: /tmp/whylogs-container.tar


  publish_docker_image:
    name: Publish the Docker image to Docker Hub
    timeout-minutes: 5
    if: ${{ !github.event.act && github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Download container artifact
        uses: actions/download-artifact@v2
        with:
          name: container
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/whylogs-container.tar
          docker tag whylabs/whylogs:py-${{ github.sha }} whylabs/whylogs:py-latest
          docker image ls -a
      - name: Push Docker container
        run: |
          docker push whylabs/whylogs:py-${{ github.sha }}
          docker push whylabs/whylogs:py-latest
